### ISSUE TITLE
Updating properties on shared collections

### ISSUE THREAD

**Issue by Reettaphant** [guardian/facia-tool#153]
If a collection metadata property is edited on a shared collections, the new, edited value of the collection will only appear on the other fronts that the collection is included in after a page refresh.

**Comment by jennygrahamjones** [comment]
@Reettaphant I don't believe this is an issue in the tool anymore. Are you happy for us to close this?

**Comment by jonathonherbert** [comment]
Belatedly agreeing with @jennygrahamjones 😀
