### ISSUE TITLE
Post migration tasks

### ISSUE THREAD

**Issue by lindseydew** [guardian/facia-tool#8]
- [x] Delete the apps that are not facia-tool
- [x] Stop building the whole frontend stack on teamcity
- [x] Delete all frontend config
- [x] Migrate to travis?
- [x] Create some radiator graphs
- [x] Investigate npm intermittent failures on teamcity
- [x] Add logs to the logging server
- [x] Remove `facia-tool` from `frontend`

**Comment by piuccio** [comment]
> Stop building the whole frontend stack on teamcity

Fixed in #11

**Comment by piuccio** [comment]
> Delete the apps that are not facia-tool
fixed in #12 

> Add logs to the logging server
done in #20 

> Remove facia-tool from frontend
done on frontend repo, who cares

**Comment by piuccio** [comment]
all done
